### ISSUE TITLE
Unclear motivation for this repo

### ISSUE THREAD

**Issue by xi** [xi/apca-introduction#13]
@myndex wrtoe in https://github.com/xi/apca-introduction/issues/7#issuecomment-1213078955:

> My question to you is why? Did you decide to develop this on your own? Or who or what group encouraged you to "analyze" the math while fully ignoring all of the underlying vision science?

**Comment by xi** [comment]
APCA was mentioned in a [WCAG working draft](https://www.w3.org/TR/2021/WD-wcag-3.0-20211207/). So, according to the principle of [wide review](https://www.w3.org/2021/Process-20211102/#dfn-wide-review) it is kinda my job as a web developer to review it and provide comments.

I soon realized that the official documentation was not very helpful to me, so I decided to publish my notes in a more structured way to help both me and other people to review APCA. A stated in the README:

> For one it was born out of my personal frustration with the original documentation. Some important pieces of information (e.g. the actual algorithm) get buried under all that text.
>
> The original documentation also contains absolute statements like "APCA is perceptually uniform" and that the old algorithm produces "invalid results". This in my opinion is wrong as perceptual uniformity is an ideal that can never be reached completely. So I felt like there was room for a more balanced introduction.

**Comment by Myndex** [comment]
> _I soon realized that the official documentation was not very helpful to me_

Did you actually read it? Because my interactions with you make it seem that you did not.

The LaTeX of the formula is literally the FIRST file in the folder labeled "documentation". And the only actual criticism you made to me at the repo was that you could not find the formula. This implies that you did not even look in the folder labeled documentation.

If you don't want to read the documentation, I don't know what to tell you.

If you do not understand the documentation as written, then that is obviously my bad and I need to correct that. But you have thus far failed to make any actionable comments in that regard.

**Comment by Myndex** [comment]
> _...it is kinda my job as a web developer to review it and provide comments._

Are you also known as user JAWS-test? What is your relationship to other past or current members of the W3C?
