### ISSUE TITLE
"All models are wrong....but some models are useful"

### ISSUE THREAD

**Issue by Myndex** [xi/apca-introduction#8]
I see the recent addition of a truncated quote from George Box to support your position.

### Here is a more complete quote from Box:

_"It has been said that 'all models are wrong but some models are useful.' In other words, any model is at best a useful fiction—there never was, or ever will be, an exactly normal distribution or an exact linear relationship. Nevertheless, enormous progress has been made by entertaining such fictions and using them as approximations."_

### _MY OBJECTION_
You can not just hand wave the "all models are wrong" aphorism around out of context like this unless you are trying to sway laypersons unaware of the real contextual value of the statement. For the record, George Box was a brilliant statistician, though not a vision scientist. Nevertheless, statistics is the foundation of much of science, and particular in the science of modeling phenomena. We know all too well that no vision model is "absolute" but we do have models that are more than accurate enough to very useful work.

A model does not need to encompass 100% of the parameters to be useful. But the parameters it _DOES_ use must be connected to actual characteristics / measured data. The ultimate goal is an irreducible simplicity, but **never a naive approach**. 

What you label as the naive approach is simply incorrect in total. The 0.4 **_is_** the naive approach.

Your 0.4 is a "guess" as you youself called it, and thus is unsuppartable and notwithstanding. Nothing about the 0.4 addition is relatable to any true or measured phenomena. Again, it is nothing more than a brute force attempt to reverse engineer curves that are derived from measured phenomena.

There are ample data sets of measured vision characteristics that can be used to validate models. That might be a good place for you to start.

PARTING SHOT:

To translate the phrase "All models are wrong" from that of insider knowledge of statistics, to that of plain language for the layperson, the actual phrase should be:

_"No model is perfect, but well developed models give useful results".
—Andrew Somers_

**Comment by xi** [comment]
Thanks for this discussion of the quote. I largely agree with the points you make.

In this context I would translate it as "no contrast formula perfectly predicts how humans will perceive contrast, but APCA might do a better job than WCAG 2.x". I am trying to learn enough about APCA to understand how to asses whether that is the case. It may be obvious to you (as we are discussing in #6), but I do not have your background in color science and need more explanation.

Note that a model is not necessarily "more useful" because it is "more accurate". There are other things to consider like usability, ease of implementation, stability against computational errors etc. So in some rare cases a naive approach can be "more useful" than a more complex one. Also, a naive approach can help us understand why a more complex approach is needed.

> You can not just hand wave the "all models are wrong" aphorism around out of context like this unless you are trying to sway laypersons unaware of the real contextual value of the statement. […] We know all too well that no vision model is "absolute" but we do have models that are more than accurate enough to very useful work.

So what exactly is your objection? Isn't that exactly what the quote says?

> There are ample data sets of measured vision characteristics that can be used to validate models. That might be a good place for you to start.

I am very interested in that. I searched for datasets for contrast vision but could not find any. Can you point me to where I can find them?

**Comment by Myndex** [comment]
> _Note that a model is not necessarily "more useful" because it is "more accurate". There are other things to consider like usability, ease of implementation, stability against computational errors etc._ 

Making a model naive (as you have) for the purpose of simplicity is equally corrupt.

**Comment by Myndex** [comment]
> So what exactly is your objection? Isn't that exactly what the quote says?

LOL. That's disingenuous. It is loaded language, intended for use only within the circle of statisticians. it fails plain language. The plain language quote is:

_"No model is perfect, but well developed models give useful results"._

**Comment by xi** [comment]
This is a well known quote that has a well known meaning. I will not remove it just because you think it could be misunderstood.

**Comment by Myndex** [comment]
> _This is a well known quote that has a well known meaning. I will not remove it just because you think it could be misunderstood._

LOL. It is well known in math and statistics.
